version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: oas-praxis/server
    container_name: server
    restart: always
    tty: true
    volumes:
      - ./server/lib:/var/www/html
      - /var/www/html/vendor/
    ports:
      - 8001:80
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: oas-praxis/client
    container_name: client
    restart: always
    tty: true
    volumes:
      - ./client:/var/www/html
      - /var/www/html/vendor/
    ports:
      - 8000:80
    depends_on:
      - server
